<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2012 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Content elements
 */
$GLOBALS['TL_LANG']['CTE']['moofxslide'] 		= 'Mootools Fx.Slide';
$GLOBALS['TL_LANG']['CTE']['moofxslideStart'] 	= array('Fx.Slide Umschlag Anfang', 'Öffnet ein mootools Fx.Slide-Element.');
$GLOBALS['TL_LANG']['CTE']['moofxslideStop'] 	= array('Fx.Slide Umschlag Ende', 'Schliesst ein mootools Fx.Slide-Element.');
$GLOBALS['TL_LANG']['CTE']['moofxslideSingle'] 	= array('Fx.Slide Einzelelement', 'Erzeugt ein mootools Fx.Slide-Element.');
