<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2012 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Content elements
 */
$GLOBALS['TL_LANG']['CTE']['moofxslide'] = array('Mootools Fx.Slide', 'Erzeugt ein mootools Fx.Slide-Element.');

?>