<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2012 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_content']['mooType_slide']		= array('Betriebsart', 'Bitte wählen Sie die Betriebsart des Slide-Elements.');
$GLOBALS['TL_LANG']['tl_content']['slidesingle']        = array('Einzelnes Element', 'Entspricht einem Text-Inhaltselement in einem Slide-Fenster.');
$GLOBALS['TL_LANG']['tl_content']['slidestart']         = array('Umschlag Anfang', 'Markiert den Anfang eines Slide-Fensters, das mehrere Inhaltselemente umfasst.');
$GLOBALS['TL_LANG']['tl_content']['slidestop']          = array('Umschlag Ende', 'Markiert das Ende eines Slide-Fensters, das mehrere Inhaltselemente umfasst.');
$GLOBALS['TL_LANG']['tl_content']['mooHeadline_slide']   = array('Bereichsüberschrift', 'Bitte geben Sie die Überschrift des Slide-Fensters ein. HTML-Tags sind erlaubt.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_content']['moo_slide_legend'] 	= 'Slide-Einstellungen';

?>